name: ecommers
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_lints: ^4.0.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  mocktail: ^1.0.4
  mockito: ^5.4.4
  http: ^1.2.2
  build_runner: ^2.4.11
  collection: ^1.18.0
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.3.1
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  get_it: ^7.7.0
  image_field: ^0.0.10
  firebase_storage: ^11.6.0
  supabase_flutter: ^2.6.0
  file_picker: ^8.1.1
  permission_handler: ^11.3.1
  http_parser: ^4.0.2
  flutter_easyloading: ^3.0.5
  email_validator: ^3.0.0
  date_formatter: ^0.0.4
  animated_splash_screen: ^1.3.0
  searchfield: ^1.0.9
  socket_io_client: ^2.0.3+1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CaveatBrush
      fonts:
        - asset: assets/FontFamily/Caveat_Brush/CaveatBrush-Regular.ttf
  #         style: italic
    - family: Poppins
      fonts:
        - asset: assets/FontFamily/Poppins/Poppins-Black.ttf
        - asset: assets/FontFamily/Poppins/Poppins-Bold.ttf
        - asset: assets/FontFamily/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/FontFamily/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/FontFamily/Poppins/Poppins-Light.ttf
        - asset: assets/FontFamily/Poppins/Poppins-Medium.ttf
        - asset: assets/FontFamily/Poppins/Poppins-Regular.ttf
        - asset: assets/FontFamily/Poppins/Poppins-SemiBold.ttf
        - asset: assets/FontFamily/Poppins/Poppins-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
