name: "ecommerce_app_ca_tdd"
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_image_compress: ^2.3.0
  flutter_native_splash: ^2.4.1
  get: null
  get_it: ^7.2.0
  google_fonts: 6.2.1
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  mockito: ^5.4.4
  page_transition: ^2.1.0
  popover: ^0.3.0+1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  

dev_dependencies:
  build_runner: ^2.4.11
  build_test: ^2.2.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/shoes.jpg
    - assets/icons8-notification-bell-48.png
    - assets/icons8-notification-bell-24.png
    - assets/jeff.jpg
    - assets/zachary-keimig-V_aqnVipk-s-unsplash.jpg
    - assets/mike.jpg
    - assets/hightpop.jpg
    - assets/will.jpg
    - assets/splash.jpg
    - assets/girls.png

fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.otf
  # - family: ATOP
  #   fonts:
  #     - asset: fonts/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/AppLogo.png
  android: true
  ios: true
